# NumPy کار با کتابخانه

## محاسبات آرایه ای و برداری

NumPy, short for Numerical Python, is the fundamental package required for high
performance scientific computing and data analysis.

In [1]:
import numpy as np

#### The NumPy ndarray: A Multidimensional Array Object

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data1*2

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [8]:
arr1*2

array([12., 15., 16.,  0.,  2.])

In [3]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

In [11]:
arr2.dtype

dtype('int32')

In [14]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
arr4 = np.empty((2, 3, 2))
arr4 

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
arr5=np.arange(15)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## نوع داده های درون یک آرایه

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

### Basic Indexing and Slicing

In [29]:
arr = np.arange(10)

In [30]:
arr[5]

5

In [31]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr[5:8]

array([12, 12, 12])

An important first distinction from lists is that array slices are views on the original array. This means that
the data is not copied, and any modifications to the view will be reflected in the source
array:

In [34]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### 2D Array

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [38]:
 arr2d[0][2]

3

In [39]:
arr2d[0, 2]

3

### 3D Array

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Indexing with slices

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [47]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### Boolean Indexing

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.rand(7, 4)

In [63]:
data

array([[0.5940285 , 0.16417591, 0.52233894, 0.85605748],
       [0.34348262, 0.90131145, 0.53685494, 0.97312049],
       [0.11591739, 0.42975735, 0.73122554, 0.53390834],
       [0.39680451, 0.63636575, 0.81007733, 0.63107673],
       [0.01589622, 0.44108792, 0.50709551, 0.989041  ],
       [0.79892216, 0.19151574, 0.257064  , 0.79713408],
       [0.62627925, 0.80230446, 0.54149583, 0.46157131]])

In [64]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [65]:
data[names == 'Bob']

array([[0.5940285 , 0.16417591, 0.52233894, 0.85605748],
       [0.39680451, 0.63636575, 0.81007733, 0.63107673]])

In [66]:
data[names == 'Bob', 2:]

array([[0.52233894, 0.85605748],
       [0.81007733, 0.63107673]])

In [67]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [69]:
data[~(names == 'Bob')]

array([[0.34348262, 0.90131145, 0.53685494, 0.97312049],
       [0.11591739, 0.42975735, 0.73122554, 0.53390834],
       [0.01589622, 0.44108792, 0.50709551, 0.989041  ],
       [0.79892216, 0.19151574, 0.257064  , 0.79713408],
       [0.62627925, 0.80230446, 0.54149583, 0.46157131]])

In [71]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [72]:
data[mask]

array([[0.5940285 , 0.16417591, 0.52233894, 0.85605748],
       [0.11591739, 0.42975735, 0.73122554, 0.53390834],
       [0.39680451, 0.63636575, 0.81007733, 0.63107673],
       [0.01589622, 0.44108792, 0.50709551, 0.989041  ]])

In [74]:
data[data < 0] = 0
data

array([[0.5940285 , 0.16417591, 0.52233894, 0.85605748],
       [0.34348262, 0.90131145, 0.53685494, 0.97312049],
       [0.11591739, 0.42975735, 0.73122554, 0.53390834],
       [0.39680451, 0.63636575, 0.81007733, 0.63107673],
       [0.01589622, 0.44108792, 0.50709551, 0.989041  ],
       [0.79892216, 0.19151574, 0.257064  , 0.79713408],
       [0.62627925, 0.80230446, 0.54149583, 0.46157131]])

## Fast Element-wise Array Functions

In [77]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Mathematical and Statistical Methods

In [82]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()

0.11533865520108774

In [83]:
np.mean(arr)

0.11533865520108774

In [84]:
arr.sum()

2.306773104021755

In [85]:
arr.mean(axis=1)

array([-0.39715581, -0.46969899,  0.5678528 ,  0.27263869,  0.60305659])

In [86]:
arr.sum(0)

array([ 4.84559911, -2.46687004, -0.92680604,  0.85485008])

In [88]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [89]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)