# NumPy کار با کتابخانه

## باز شکل دادن یک آرایه 

In [155]:
import numpy as np
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
b = a.reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [56]:
b=np.array(range(8)).reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [60]:
b.flatten() 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
b.flatten(order = 'F')

array([0, 2, 4, 6, 1, 3, 5, 7])

## توابع ریاضی در آرایه ها

In [156]:
import numpy as np
import math as m

In [157]:
m.sqrt(2)

1.4142135623730951

In [158]:
np.sqrt(2)

1.4142135623730951

In [31]:
m.sqrt([2,3])

TypeError: must be real number, not list

In [163]:
np.sqrt([2,3])

array([1.41421356, 1.73205081])

In [164]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [165]:
np.cos(b*np.pi/180)

array([[1.        , 0.9998477 ],
       [0.99939083, 0.99862953],
       [0.99756405, 0.9961947 ],
       [0.9945219 , 0.99254615]])

In [166]:
a = np.array([1.0,5.55, 123, 0.567, 25.432]) 
np.around(a)

array([  1.,   6., 123.,   1.,  25.])

In [167]:
np.around(a,1)

array([  1. ,   5.6, 123. ,   0.6,  25.4])

In [41]:
np.floor(a)

array([  1.,   5., 123.,   0.,  25.])

In [42]:
np.ceil(a)

array([  1.,   6., 123.,   1.,  26.])

## توابع آماری در آرایه ها

In [66]:
list1 = [2,3,4,5,6]
arr1 = np.array(list1)
arr1.mean()

4.0

In [67]:
np.mean(arr1)

4.0

In [69]:
arr1.sum()

20

In [169]:
a = np.array([[3,7,5,6],[8,4,3,2],[2,4,9,1]]) 
a

array([[3, 7, 5, 6],
       [8, 4, 3, 2],
       [2, 4, 9, 1]])

In [170]:
a.mean()

4.5

In [171]:
a.mean(0)

array([4.33333333, 5.        , 5.66666667, 3.        ])

In [172]:
a.mean(axis=1)

array([5.25, 4.25, 4.  ])

In [84]:
a.sum(0)

array([13, 15, 17,  9])

In [85]:
a.cumsum(0)

array([[ 3,  7,  5,  6],
       [11, 11,  8,  8],
       [13, 15, 17,  9]], dtype=int32)

In [175]:
a.cumprod(1)

array([[  3,  21, 105, 630],
       [  8,  32,  96, 192],
       [  2,   8,  72,  72]], dtype=int32)

In [176]:
a

array([[3, 7, 5, 6],
       [8, 4, 3, 2],
       [2, 4, 9, 1]])

In [174]:
a.min(0)

array([2, 4, 3, 1])

In [96]:
np.min(a,0)

array([2, 4, 3, 1])

In [177]:
np.max(a,1)

array([7, 8, 9])

In [97]:
np.median(a, axis = 1)

array([5.5, 3.5, 3. ])

In [99]:
np.percentile(a,50, axis = 0)

array([3., 4., 5., 2.])

In [178]:
np.std(a, axis = 1)

array([1.47901995, 2.27760839, 3.082207  ])

In [179]:
a.std(1)

array([1.47901995, 2.27760839, 3.082207  ])

In [104]:
np.var(a, axis = 1)

array([2.1875, 5.1875, 9.5   ])

In [181]:
a.var(1)

array([2.1875, 5.1875, 9.5   ])

## توابع مرتب سازی، شمارشی و جستجو در آرایه 

In [182]:
a = np.array([2,4,2,8,3,5,4,8,1])
a.sort()
a

array([1, 2, 2, 3, 4, 4, 5, 8, 8])

In [183]:
a[::-1]

array([8, 8, 5, 4, 4, 3, 2, 2, 1])

In [184]:
a = np.array([2,4,2,8,3,5,4,8,1])
np.sort(a)

array([1, 2, 2, 3, 4, 4, 5, 8, 8])

In [185]:
a

array([2, 4, 2, 8, 3, 5, 4, 8, 1])

In [124]:
a = np.array(['zahra','ali','mohammad'])
np.sort(a)

array(['ali', 'mohammad', 'zahra'], dtype='<U8')

In [188]:
a = np.array([[3,7,5,6],[8,4,3,2],[2,4,9,1]]) 
a

array([[3, 7, 5, 6],
       [8, 4, 3, 2],
       [2, 4, 9, 1]])

In [190]:
np.sort(a, axis = 1)

array([[3, 5, 6, 7],
       [2, 3, 4, 8],
       [1, 2, 4, 9]])

In [131]:
np.sort(a, axis = 0)

array([[2, 4, 3, 1],
       [3, 4, 5, 2],
       [8, 7, 9, 6]])

In [133]:
a = np.array([2,4,2,12,3,5,4,8,1])
np.argmax(a) 

3

In [134]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [135]:
np.argmax(a) 

7

In [137]:
np.argmax(a, axis = 0)

array([1, 2, 0], dtype=int64)

In [139]:
 np.argmin(a, axis = 0) 

array([0, 1, 1], dtype=int64)

In [142]:
a = np.array([2,4,2,12,3,5,4,8,1])
np.where(a > 3) 

(array([1, 3, 5, 6, 7], dtype=int64),)

In [150]:
a = np.array([[0,0,7],[0,2,1],[0,9,6]]) 
a

array([[0, 0, 7],
       [0, 2, 1],
       [0, 9, 6]])

In [153]:
np.where(a > 5) 

(array([0, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [154]:
np.extract(a>5, a)

array([7, 9, 6])