 <h1 style="text-align: justify; direction:rtl"> 
   درس 9: کار با کتابخانه NumPy 
</h1>

 <h2 style="text-align: justify; direction:rtl"> 
  محاسبات آرایه ای و برداری 
</h2>

NumPy, short for Numerical Python, is the fundamental package required for high
performance scientific computing and data analysis.

In [1]:
import numpy as np

#### The NumPy ndarray: A Multidimensional Array Object

In [7]:
list1 = [4, 7, 8, 0, 1]
arr1 = np.array(list1)
arr1

array([4, 7, 8, 0, 1])

In [169]:
tuple1 = (6, 7, 8, 0, 1)
arr1 = np.array(tuple1,dtype=float)
arr1

array([6., 7., 8., 0., 1.])

In [147]:
tuple1 = (6, 7.5, 8, 0, 1)
arr1 = np.array(tuple1,dtype=int)
arr1

array([6, 7, 8, 0, 1])

In [145]:
list1*2

[6, 7.5, 8, 0, 1, 6, 8, 3, 6, 7.5, 8, 0, 1, 6, 8, 3]

In [32]:
arr1*2

array([12., 15., 16.,  0.,  2.])

In [148]:
list1+1

TypeError: can only concatenate list (not "int") to list

In [9]:
arr1/3

array([1.33333333, 2.33333333, 2.66666667, 0.        , 0.33333333])

In [11]:
list2=[1,2,1,3,1]
arr2 = np.array(list2)
arr2

array([1, 2, 1, 3, 1])

In [12]:
list1*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
arr1*arr2

array([ 4, 14,  8,  0,  1])

In [15]:
arr3=np.array([1,4])
arr1*arr3

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

### آرایه های با بعد بالاتر از 1

In [16]:
list3 = [[1, 2.3, 3, 4], [5, 6, 7, 8]]
arr3 = np.array(list3)
arr3

array([[1. , 2.3, 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [17]:
arr3.shape

(2, 4)

In [18]:
arr3.dtype

dtype('float64')

### استفاده از آرایه های پیش ساخته

In [22]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
x.dtype

dtype('float64')

In [187]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [188]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [77]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [78]:
np.ones((3, 6),dtype=str)

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [64]:
np.arange(3,15,2,dtype=float)

array([ 3.,  5.,  7.,  9., 11., 13.])

In [71]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 <h2 style="text-align: justify; direction:rtl"> 
 جداکردن زیر آرایه ها  
</h2>

### 1-integer indexing

In [89]:
list1 = [6, 7.5, 8, 0, 1,6,8,3]
arr1 = np.array(list1)
arr1

array([6. , 7.5, 8. , 0. , 1. , 6. , 8. , 3. ])

In [91]:
list1[1:4]

[7.5, 8, 0]

In [93]:
arr1[1:4]

array([7.5, 8. , 0. ])

In [96]:
list1[::2]

[6, 8, 1, 8]

In [189]:
arr1[::2]

array([6., 8., 1.])

In [196]:
list1[[2,4]]

TypeError: list indices must be integers or slices, not tuple

In [199]:
arr1[[2,4]]

array([8., 1.])

In [25]:
list2 = [[1, 2, 3, 4], [5, 6, 7, 8],[3,5,3,2]]
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 3, 2]])

In [201]:
list2[1]

[5, 6, 7, 8]

In [202]:
arr2[1]

array([5, 6, 7, 8])

In [110]:
list2[1][1]

6

In [26]:
arr2[1][1]

6

In [28]:
arr2[1,1]

6

In [27]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 3, 2]])

In [116]:
arr2[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [119]:
arr2[:,1]

array([2, 6, 5])

In [29]:
arr2[[0,2],[1,3]]

array([2, 2])

In [30]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 3, 2]])

In [203]:
rows = np.array([[0,0],[2,2]])
cols = np.array([[0,2],[0,3]])
arr2[rows,cols] 

array([[1, 3],
       [3, 2]])

In [31]:
rows = np.array([[0,2],[1,2]])
cols = np.array([[0,1],[1,2]])
arr2[rows,cols]

array([[1, 5],
       [6, 3]])

### 2-boolean indexing

In [128]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 3, 2]])

In [130]:
arr2>3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False, False]])

In [32]:
arr2[arr2>3]

array([4, 5, 6, 7, 8, 5])

In [34]:
arr2%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False, False, False,  True]])

In [137]:
arr2[arr2%2==0]

array([2, 4, 6, 8, 2])

In [2]:
#NaN (Not a Number)
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [4]:
~np.isnan(a)

array([False,  True,  True, False,  True,  True,  True])

In [5]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

An important first distinction from lists is that array slices are views on the original array. This means that
the data is not copied, and any modifications to the view will be reflected in the source
array:

In [208]:
x = np.arange(8)
x_slice = x[5:8]
x_slice[1] = 12345
x

array([    0,     1,     2,     3,     4,     5, 12345,     7])

In [210]:
x_slice[:] = 64
x

array([ 0,  1,  2,  3,  4, 64, 64, 64])

In [217]:
x = np.arange(8)
x_slice2 = x[5:8].copy()
x_slice2[1] = 12345
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [218]:
x_slice2

array([    5, 12345,     7])

 <h2 style="text-align: justify; direction:rtl"> 
   باز شکل دادن یک آرایه
</h2>

In [8]:
import numpy as np
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
b = a.reshape(4,2).copy()
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
b.shape

(4, 2)

In [11]:
b[0,1] = 11
print(a)

[0 1 2 3 4 5 6 7]


In [13]:
b=np.array(range(8)).reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
c = np.array([3,4,5,6,7,4]).reshape(2,3)
c

array([[3, 4, 5],
       [6, 7, 4]])

In [15]:
c.flatten() 

array([3, 4, 5, 6, 7, 4])

In [18]:
c.flatten(order = 'F')

array([3, 6, 4, 7, 5, 4])

 <h2 style="text-align: justify; direction:rtl"> 
توابع ریاضی در نامپای
</h2>

In [6]:
import numpy as np
import math as m


In [7]:
m.sqrt(2)

1.4142135623730951

In [8]:
np.sqrt(2)

1.4142135623730951

In [9]:
m.sqrt([2,3])

TypeError: must be real number, not list

In [10]:
np.sqrt([2,3])

array([1.41421356, 1.73205081])

In [8]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
np.cos(b*np.pi/180)

array([[1.        , 0.9998477 ],
       [0.99939083, 0.99862953],
       [0.99756405, 0.9961947 ],
       [0.9945219 , 0.99254615]])

In [13]:
a = np.array([1.0,5.55, 123, 0.567, 25.432]) 
np.around(a)

array([  1.,   6., 123.,   1.,  25.])

In [14]:
np.around(a,1)

array([  1. ,   5.6, 123. ,   0.6,  25.4])

In [15]:
np.floor(a)

array([  1.,   5., 123.,   0.,  25.])

In [16]:
np.ceil(a)

array([  1.,   6., 123.,   1.,  26.])

<h2 style="text-align: justify; direction:rtl"> 
توابع آماری در آرایه ها
</h2>


In [20]:
list1 = [2,3,4,5,6]
arr1 = np.array(list1)
arr1.mean()

4.0

In [13]:
np.mean(arr1)

4.0

In [21]:
arr1.sum()

20

In [22]:
np.sum(arr1)

20

In [23]:
sum(arr1)

20

In [16]:
np.min(arr1)

2

In [18]:
a = np.array([[3,7,5,6],[8,4,3,2],[2,4,9,1]]) 
a

array([[3, 7, 5, 6],
       [8, 4, 3, 2],
       [2, 4, 9, 1]])

In [19]:
a.mean()

4.5

In [20]:
a.mean(0)

array([4.33333333, 5.        , 5.66666667, 3.        ])

In [24]:
a.mean(1)

array([5.25, 4.25, 4.  ])

In [25]:
a

array([[3, 7, 5, 6],
       [8, 4, 3, 2],
       [2, 4, 9, 1]])

In [26]:
a.sum(0)

array([13, 15, 17,  9])

In [28]:
np.sum(a,0)

array([13, 15, 17,  9])

In [23]:
a.cumsum(0)

array([[ 3,  7,  5,  6],
       [11, 11,  8,  8],
       [13, 15, 17,  9]], dtype=int32)

In [26]:
a.cumprod(1)

array([[  3,  21, 105, 630],
       [  8,  32,  96, 192],
       [  2,   8,  72,  72]], dtype=int32)

In [27]:
a.min(0)

array([2, 4, 3, 1])

In [28]:
np.min(a,0)

array([2, 4, 3, 1])

In [29]:
np.max(a,1)

array([7, 8, 9])

In [30]:
np.median(a, axis = 1)

array([5.5, 3.5, 3. ])

In [29]:
np.percentile(a,50, axis = 1)

array([5.5, 3.5, 3. ])

In [30]:
np.std(a, axis = 1)

array([1.47901995, 2.27760839, 3.082207  ])

In [31]:
a.std(1)

array([1.47901995, 2.27760839, 3.082207  ])

In [32]:
np.var(a, axis = 1)

array([2.1875, 5.1875, 9.5   ])

In [35]:
a.var(1)

array([2.1875, 5.1875, 9.5   ])

<h2 style="text-align: justify; direction:rtl"> 
توابع مرتب سازی، شمارشی و جستجو در آرایه
</h2>

In [36]:
a = np.array([2,4,2,8,3,5,4,8,1])
a.sort()
a

array([1, 2, 2, 3, 4, 4, 5, 8, 8])

In [37]:
a[::-1]

array([8, 8, 5, 4, 4, 3, 2, 2, 1])

In [38]:
a = np.array([2,4,2,8,3,5,4,8,1])
np.sort(a)

array([1, 2, 2, 3, 4, 4, 5, 8, 8])

In [39]:
a = np.array(['zahra','ali','mohammad'])
np.sort(a)

array(['ali', 'mohammad', 'zahra'], dtype='<U8')

In [40]:
a = np.array([[3,7,5,6],[8,4,3,2],[2,4,9,1]]) 
a

array([[3, 7, 5, 6],
       [8, 4, 3, 2],
       [2, 4, 9, 1]])

In [41]:
np.sort(a, axis = 1)

array([[3, 5, 6, 7],
       [2, 3, 4, 8],
       [1, 2, 4, 9]])

In [42]:
np.sort(a, axis = 0)

array([[2, 4, 3, 1],
       [3, 4, 5, 2],
       [8, 7, 9, 6]])

In [43]:
a = np.array([2,4,2,12,3,5,4,8,1])
np.argmax(a) 

3

In [44]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [45]:
np.argmax(a) 

7

In [46]:
np.argmax(a, axis = 0)

array([1, 2, 0], dtype=int64)

In [47]:
 np.argmin(a, axis = 0) 

array([0, 1, 1], dtype=int64)

In [48]:
a = np.array([2,4,2,12,3,5,4,8,1])
np.where(a > 3)

(array([1, 3, 5, 6, 7], dtype=int64),)

In [34]:
a = np.array([[0,0,7],[0,2,1],[0,9,6]]) 
a

array([[0, 0, 7],
       [0, 2, 1],
       [0, 9, 6]])

In [50]:
np.where(a > 5) 

(array([0, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [51]:
np.extract(a>5, a)

array([7, 9, 6])

In [37]:
a[a>5]

array([7, 9, 6])